---
- name: Install PoE+ Hat
  hosts: k8s
  become: yes

  tasks:
    - name: Update repo cache
      apt:
        update_cache: yes

    - name: Update installed software
      apt:
        upgrade: safe

    - name: Fan Config
      ansible.builtin.template:
        src: templates/boot-config.txt
        dest: /boot/config.txt
        owner: root
        group: root
        mode: u=rw

    - name: Reboot pi
      reboot:
        reboot_timeout: 120
