---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app.kubernetes.io/name: ntfy
  name: ntfy
  namespace: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
    spec:
      containers:
        - name: ntfy
          image: binwiederhier/ntfy
          imagePullPolicy: Always
          args:
            - "serve"
          ports:
            - name: ntfy
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/etc/ntfy"
              readOnly: true
            - name: ntfy
              mountPath: "/var/lib/ntfy"
      volumes:
        - name: config
          configMap:
            name: config
        - name: ntfy
          persistentVolumeClaim:
            claimName: ntfy

---
kind: Service
apiVersion: v1
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    metallb.universe.tf/allow-shared-ip: ntfy
spec:
  selector:
    app.kubernetes.io/name: ntfy
  ports:
    - name: ntfy
      port: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: cloudflare-issuer-dni-sh
spec:
  rules:
    - host: ntfy.dni.sh
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ntfy
                port:
                  number: 80
  tls:
    - hosts:
        - ntfy.dni.sh
      secretName: kuma-dni-sh-certificate
