---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy
  namespace: ntfy
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
