---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-api-token-dni-sh
  namespace: cert-manager
spec:
  acme:
    ...
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-dni-sh
              key: api-token
