---
- name: All Pis
  hosts: k8s

  pre_tasks:
    - name: Update repo cache
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade installed software
      become: yes
      apt:
        upgrade: safe

  roles:
    - swapless
    - poe
    - cgroups
    - legacy-iptables

  handlers:
    - name: restart pi
      reboot:
        reboot_timeout: 120
