---
- name: Everything
  hosts: k8s

  pre_tasks:
    - name: Update repo cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed software
      become: true
      apt:
        upgrade: safe

  roles:
#    - resolv
#    - legacy-iptables
    - nfs-common
    - iscsi

  handlers:
    - name: restart pi
      become: true
      reboot:
        reboot_timeout: 120

###
- name: All Pis
  hosts: pis

  roles:
#    - swapless
#    - poe
    - cgroups

  handlers:
    - name: restart pi
      become: true
      reboot:
        reboot_timeout: 120

###
- name: k8s-primary-server
  hosts: primary_server

  roles:
    - k3s-primary-server

###
- name: k8s-secondary-server
  hosts: secondary_servers

  roles:
    - k3s-secondary-server

###
- name: k8s-agent
  hosts: agents

  roles:
    - k3s-agent
