---
- name: Everything
  hosts: k8s

  pre_tasks:
    - name: Update repo cache
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed software
      become: true
      apt:
        upgrade: safe

  roles:
    - resolv
    - legacy-iptables
    - nfs-common
    - iscsi

  handlers:
    - name: restart pi
      become: true
      reboot:
        reboot_timeout: 120

###
- name: All Pis
  hosts: pis

  roles:
    - swapless
    - poe
    - cgroups

  handlers:
    - name: restart pi
      become: true
      reboot:
        reboot_timeout: 120

###
- name: k8s-master
  hosts: masters

  roles:
    - k3s-master

###
- name: k8s-node
  hosts: nodes

  roles:
    - k3s-node
