---
kind: Endpoints
apiVersion: v1
metadata:
  name: home-assistant
  namespace: routing
subsets:
  - addresses:
      - ip: 10.3.0.100
    ports:
      - name: http
        port: 8123
        protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: home-assistant
  namespace: routing
spec:
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: home-assistant
  namespace: routing
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: cloudflare-issuer-dni-sh
spec:
  rules:
    - host: ha.dni.sh
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: home-assistant
                port:
                  name: http
  tls:
    - hosts:
        - ha.dni.sh
      secretName: home-assistant-dni-sh-certificate
