---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: https://wallpapercave.com/wp/wp6524674.jpg
    
    cardBlur: md

    theme: dark

    headerStyle: boxedWidgets

    providers:

  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
#  bookmarks.yaml: |
#    - Developer:
#        - Github:
#            - abbr: GH
#              href: https://github.com/
  services.yaml: |
    - Infrastructure:
        - Unifi Console:
            widget:
              type: unifi
              url: https://10.0.0.1
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

        - PiHole:
            href: https://pihole.dni.sh/admin
            namespace: dns
            app: pihole
            icon: pi-hole
            widget:
                type: pihole
                url: https://pihole.dni.sh
                key: {{HOMEPAGE_VAR_PI_HOLE_API_KEY}}

        - Uptime Kuma:
            href: https://kuma.dni.sh
            namespace: uptime
            app: uptime-kuma
            icon: uptime-kuma
            widget:
              type: uptimekuma
              url: https://kuma.dni.sh
              slug: all

        - Grafana:
            href: https://grafana.dni.sh
            namespace: monitoring
            app: grafana
            icon: grafana
            #widget:
            #    type: grafana
            #    url: https://grafana.dni.sh
            #    username: {{GRAFANA_USERNAME}}
            #    password: {{GRAFANA_PASSWORD}}

        - Ntfy:
            href: https://ntfy.dni.sh
            namespace: ntfy
            app: ntfy
            icon: ntfy

    - Services:
        - Readarr:
            href: https://readarr.dni.sh
            namespace: servarr
            app: readarr
            icon: readarr
        

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - unifi_console:
        url: https://10.0.0.1
        username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
        password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}

    - openmeteo:
        latitude: {{HOMEPAGE_VAR_WEATHER_LAT}}
        longitude: {{HOMEPAGE_VAR_WEATHER_LONG}}
        timezone: Europe/London
        units: metric
        cache: 10 # Time in minutes to cache API responses, to stay within limits

    - search:
          provider: google # google, duckduckgo, bing, baidu, brave or custom
          focus: true # Optional, will set focus to the search bar on page load
          target: _blank # One of _self, _blank, _parent or _top

  docker.yaml: ""
