---
# tasks file for k3s-nodes
- name: Download
  get_url:
    dest: ~/k3s
    url: https://get.k3s.io
  tags:
    - always

- name: Set execute permission
  file:
    path: ~/k3s
    mode: u+x
  tags:
    - always

- name: start nodes
  shell: ~/k3s agent --disable=servicelb --server https://10.4.0.100:6443 --token {{ hostvars['10.4.0.100']['node_token'] }} &
  tags:
    - always
