---
# tasks file for k3s-server
- name: Download
  get_url:
    dest: ~/k3s
    url: https://get.k3s.io
    force: true
  tags:
    - always

- name: Set execute permission
  file:
    path: ~/k3s
    mode: u+x
  tags:
    - always

- name: start server
  shell: ~/k3s server --disable servicelb --cluster-init
  async: 10
  poll: 0
  tags:
    - always

- name: Wait for server start
  become: yes
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  tags:
    - always

- name: Get token
  become: yes
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  tags:
    - always

- name: Save token
  set_fact:
    node_token: "{{ node_token['content'] }}"
  tags:
    - always

- name: Save ip address
  set_fact:
    ip_address: "{{ inventory_hostname }}"
  tags:
    - always

- name: Modify config
  become: yes
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: '127\.0\.0\.1'
    replace: "{{ inventory_hostname }}"

- name: Get config
  become: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ../k3s-config.yaml
    flat: yes
  tags:
    - get-config
