---
# tasks file for 64bit
- name: Enable 64bit kernal
  become: yes
  lineinfile:
    path: /boot/config.txt
    line: arm_64bit=1
  register: arm64bit_upgrade

- name: Upgrade Raspberry Pi OS (first run only)
  become: yes
  shell: yes | rpi-update
  when: arm64bit_upgrade.changed

- name: restart pi
  become: yes
  reboot:
    reboot_timeout: 120
  when: arm64bit_upgrade.changed
