---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio
  namespace: factorio
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
