---
# tasks file for k3s-master
- name: start master
  shell: ~/k3s server
  async: 10
  poll: 0

- name: Wait for server start
  become: yes
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Get token
  become: yes
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Save contents
  set_fact:
    node_token: "{{ node_token['content'] }}"

- name: Get config
  become: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ../k3s-config.yaml
    flat: yes
