---
# tasks file for k3s-master
- name: Download
  get_url:
    dest: ~/k3s
    url: https://get.k3s.io
    force: true

- name: Set execute permission
  file:
    path: ~/k3s
    mode: u+x

- name: start master
  shell: ~/k3s server
  async: 10
  poll: 0

- name: Wait for server start
  become: yes
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Get token
  become: yes
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Save contents
  set_fact:
    node_token: "{{ node_token['content'] }}"

- name: Modify config
  become: yes
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: '127\.0\.0\.1'
    replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Get config
  become: yes
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ../k3s-config.yaml
    flat: yes
