---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: storage
spec:
  storageClassName: local-storage
  capacity:
    storage: 930Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/usb-device
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage-provider
              operator: In
              values:
                - "930Gi"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
  namespace: storage
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 930Gi

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: local-server-nfs
  namespace: storage
spec:
  selector:
    matchLabels:
      name: local-server-nfs
  template:
    metadata:
      labels:
        name: local-server-nfs
    spec:
      nodeSelector:
        storage-provider: "930Gi"
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine:11-arm
          env:
            - name: SHARED_DIRECTORY
              value: /exports
          ports:
            - name: nfs
              containerPort: 2049
#            - name: mountd
#              containerPort: 20048
#            - name: rpcbind
#              containerPort: 111
          securityContext:
            capabilities:
              add: ["SYS_ADMIN", "SETPCAP"]
          volumeMounts:
            - mountPath: /exports
              name: local-storage
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-storage

---
kind: Service
apiVersion: v1
metadata:
  name: local-server-nfs
  namespace: storage
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
