---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole
  namespace: dns
  annotations:
    nfs.io/storage-path: "pihole/pihole"
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: dns
  annotations:
    nfs.io/storage-path: "pihole/dnsmasq"
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
