---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: pihole
  name: pihole
  namespace: dns
spec:
  replicas: 1 # temp
  #  replicas: 2 # because its using php, we'd need to put $_SESSION into a shared store like REDIS
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: pihole
  template:
    metadata:
      labels:
        k8s-app: pihole
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker:latest
          ports:
            - containerPort: 32400
              protocol: TCP
            - containerPort: 3005
              protocol: TCP
            - containerPort: 8324
              protocol: TCP
            - containerPort: 32469
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
          env:
            - name: TZ
              value: Europe/London

          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole
            - mountPath: /etc/dnsmasq.d
              name: pihole-dnsmasq
      #        - name: unbound
      #          image: mvance/unbound:latest
      #          ports:
      #            - name: dns-tcp
      #              containerPort: 53
      #              protocol: TCP
      #            - name: dns-udp
      #              containerPort: 53
      #              protocol: UDP
      volumes:
        - name: pihole
          persistentVolumeClaim:
            claimName: pihole
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
        - name: pihole-dnsmasq-config
          configMap:
            name: pihole-dnsmasq-config
