---
kind: Endpoints
apiVersion: v1
metadata:
  name: router
  namespace: routing
subsets:
  - addresses:
      - ip: 10.4.0.1
    ports:
      - name: https
        port: 443
        protocol: TCP

---
kind: Service
apiVersion: v1
metadata:
  name: router
  namespace: routing
spec:
  clusterIP: None
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: router
  namespace: routing
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: cloudflare-issuer-dni-sh
spec:
  rules:
    - host: router.dni.sh
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: router
                port:
                  name: https
  tls:
    - hosts:
        - router.dni.sh
      secretName: router-dni-sh-certificate
