---
kind: Endpoints
apiVersion: v1
metadata:
  name: router
  namespace: routing
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - name: http
        port: 80

---
kind: Service
apiVersion: v1
metadata:
  name: router
  namespace: routing
spec:
  ports:
    - name: http
      port: 80
  selector: {}

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: router
  namespace: routing
spec:
  rules:
    - host: router.dni.sh
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: router
                port:
                  number: 80
